{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<!--<link rel="stylesheet" href="{{$baseurl}}/view/theme/pluto/login-style.css" type="text/css" media="all" />-->

